name: Build kernel on new version

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - 'config/**/version'

env:
  DEBIAN_FRONTEND: noninteractive

jobs:
  branch-from-commit:
    name: Build new kernel
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Sources
        uses: actions/checkout@main

      - name: Extract branch affected
        id: proxmox-branch
        run: |
          branch=`echo ${{ toJSON(github.event) }} | ./scripts/extract_proxmox_branch.sh`
          echo "Proxmox branch: ${branch}"
          echo "branch=${branch}" >> $GITHUB_OUTPUT

  build:
    name: Run build kernel workflow
    needs: branch-from-commit
    uses: ./.github/workflows/build-pve-kernel-container.yml
    with:
      branch: ${{ needs.branch-from-commit.outputs.branch }}
